### ISSUE TITLE
SubrowExcelSheet Support

### ISSUE THREAD

**Issue by ItsBexy** [NotNite/Alpha#14]
Certain sheets that are now classified as `SubrowExcelSheet<>` no longer display their full sheet contents correctly.

Example comparison for `ClassJobActionUI` (left is 1.0.0.0, right is 2.0.0.2)
![b2e6c42576107fe5ae3930234fcd7734](https://github.com/user-attachments/assets/9727f6b3-6f92-4c5a-8bfb-828a7a6856d5)

The index column seems aligned between both versions. However, the table in 2.0.0.2 cuts off very early (possibly stopping when the row count is reached instead of the full subrow count?). And all subrows within a row are showing identical cell values.

**Comment by NotNite** [comment]
Fixed - the Count property was wrong because I needed to check the Count of each subrow and sum it. Will do a release shortly.

**Comment by ItsBexy** [comment]
The counts are fixed, but the values still aren't right; all subrows within a row are shown as having identical cells. (ie, `1.0` through `1.9` are all the same, and so forth).

**Comment by NotNite** [comment]
Found the issue, it was in my caching code. Making another release shortly.
